### ISSUE TITLE
Please submit your codings

### ISSUE THREAD

**Issue by 20164910** [OME-2018-CMPE314/File-Reader#13]
Hi 20154439, please submit your coding that you were planning to push into your branch (e.g. search code, color, fonts etc) before you got the user certificate  error.

**Comment by 20154439** [comment]
These are the codes:

**For Search Button:**
 private void SearchBtn_Click(object sender, EventArgs e)
        {
            int index = 0;
            String temp = richTextBox.Text;
            richTextBox.Text = "";
            richTextBox.Text = temp;

            while(index < richTextBox.Text.LastIndexOf(textBox1.Text))
            {
                //Searches the text in a RichTextBox control for a string within a range of texts.
                richTextBox.Find(textBox1.Text, index, richTextBox.TextLength, RichTextBoxFinds.None);
                //Colour Selection.This is added automatically when a match is found.
                richTextBox.SelectionBackColor = Color.Yellow;
                //After a match is found the index is increased so the search won't stop at the same match again.i.e it will search for similiar match.
                index = richTextBox.Text.IndexOf(textBox1.Text, index) + 1;
            }
        }
**For Color Button:**
  private void FontCbtn_Click(object sender, EventArgs e)
        {
            ColorDialog colour = new ColorDialog();
            colour.ShowDialog();
            richTextBox.SelectionColor = colour.Color;
        }
**For Fonts Button:**
 private void FontSizeBtn_Click(object sender, EventArgs e)
        {
            FontDialog fd = new FontDialog();
            if (fd.ShowDialog() == DialogResult.OK)
            {
                richTextBox.Font = fd.Font;
            }
        }

**Comment by 20164910** [comment]
Thanks.
