### ISSUE TITLE
Synchronize your local master branches

### ISSUE THREAD

**Issue by 20164910** [OME-2018-CMPE314/File-Reader#6]
I've fixed the conflicts between the new approved changes from my branch. I therefore request all of you to please synchronize your local master branches stored on your computers and confirm if the new changes have taken effect.

**Comment by 20164910** [comment]
[How to synchronize your local GitHub repository.pdf](https://github.com/OME-2018-CMPE314/File-Reader/files/1866608/How.to.synchronize.your.local.GitHub.repository.pdf)

**Comment by 20154439** [comment]
I have synchronized the master branch and the changes have taken effect.

**Comment by 20164910** [comment]
Good to know. Now we await feedback from our tester.

**Comment by 20156247** [comment]
Thanks my local master branch synchronized successfully. I will soon comment on the testing.

**Comment by 20164910** [comment]
Glad to hear.
