### ISSUE TITLE
User cancelled certificate check

### ISSUE THREAD

**Issue by 20154439** [OME-2018-CMPE314/File-Reader#8]
I have an issue.
when i try to create a new pull request i get an error message "User cancelled certificate check"
Any ideas on how to fix this?

**Comment by 20164910** [comment]
I did not come across that issue yet. When I read the same scenarios of other users, they mentioned something about a windows7 issue. 
They also mentioned something about updating Visual studios might help.

Have you tried creating a repository via the desktop platform, maybe that could work?

**Comment by 20154439** [comment]
These are the code that can't push.
private void selectFileBtn_Click(object sender, EventArgs e)
        {
            //declaring an object to open file dialog
            OpenFileDialog ofdlg = new OpenFileDialog();

            //condition that checks if the dialog has been opened
            if (ofdlg.ShowDialog() == DialogResult.OK)
            {
                //to enable program to read the text from file
                //gave any name to stream reader object as long as its not reserved
                StreamReader readFile = new StreamReader(File.OpenRead(ofdlg.FileName));

                //enable the rich text box to display content in selected opened text file
                richTextBox.Text = readFile.ReadToEnd();
                //closes the StreamReader method to prevent error
                //when user attempts to click the open button more than once
                readFile.Dispose();
            }

        }

        private void SearchBtn_Click(object sender, EventArgs e)
        {
            int index = 0;
            String temp = richTextBox.Text;
            richTextBox.Text = "";
            richTextBox.Text = temp;

            while(index < richTextBox.Text.LastIndexOf(textBox1.Text))
            {
                //Searches the text in a RichTextBox control for a string within a range of texts.
                richTextBox.Find(textBox1.Text, index, richTextBox.TextLength, RichTextBoxFinds.None);
                //Colour Selection.This is added automatically when a match is found.
                richTextBox.SelectionBackColor = Color.Yellow;
                //After a match is found the index is increased so the search won't stop at the same match again.i.e it will search for similiar match.
                index = richTextBox.Text.IndexOf(textBox1.Text, index) + 1;
            }
        }

        private void richTextBox_TextChanged(object sender, EventArgs e)
        {

        }

        private void SaveAFileBtn_Click(object sender, EventArgs e)
        {
            SaveFileDialog saveFileDialog = new SaveFileDialog();
            if (saveFileDialog.ShowDialog()==DialogResult.OK)
            {
                //
                using (Stream s = File.Open(saveFileDialog.FileName, FileMode.CreateNew))
                using (StreamWriter sw = new StreamWriter(s))
                {
                    sw.Write(richTextBox.Text);
                }
            }
        }

        private void FontSizeBtn_Click(object sender, EventArgs e)
        {
            FontDialog fd = new FontDialog();
            if (fd.ShowDialog() == DialogResult.OK)
            {
                richTextBox.Font = fd.Font;
            }
        }

        private void FontCbtn_Click(object sender, EventArgs e)
        {
            ColorDialog colour = new ColorDialog();
            colour.ShowDialog();
            richTextBox.SelectionColor = colour.Color;
        }

        private void ClearBtn_Click(object sender, EventArgs e)
        {
            richTextBox.Clear();
        }
    }
}

Please Assist.

**Comment by 20164910** [comment]
Since your GitHub Visual studio extension is not working, copy the codes from the master branch to your own branch and send a pull request.

**Comment by 20154439** [comment]
Ok i have done it.
